# Team Work 



## Work Packages 

[Describe all work packages]

Tahble @tbl-wps contains all work packages defined for this project.

+-------------+--------------------------------+-----------------+
| Package No. | Description                    | Responsible     |
+=============+================================+=================+
| 1           | Create AlexNet                 | Marvin          |
+-------------+--------------------------------+-----------------+
| 2           | Evaluate Object Detectors      | Marvin          |
+-------------+--------------------------------+-----------------+
| 3           | Dataloader Advancements        | Marvin          |
|             | (Augmentation, Equal           |                 |
|             | Distribution, In-Memory,       |                 |
|             | Ignore Labels ...)             |                 |
+-------------+--------------------------------+-----------------+
| 4           | Preprocessing                  | Marvin          |
+-------------+--------------------------------+-----------------+
| 5           | Filter interior images         | Marvin          |
+-------------+--------------------------------+-----------------+
| 6           | General Training Improvement   | Marvin          |
+-------------+--------------------------------+-----------------+
| 7           | Transferlearning: Resnet50     | Simon           |
|             | architecture with freezing     |                 |
|             | of the weights for our         |                 |
|             | application                    |                 |
+-------------+--------------------------------+-----------------+
| 8           | Transferlearning: Resnet50     | Simon           |
|             | architecture with finetuning   |                 |
|             | of the weights for our         |                 |
|             | application                    |                 |
+-------------+--------------------------------+-----------------+
| 9           | Implement basic dataloader     | Simon           |
+-------------+--------------------------------+-----------------+
| 10          | Article Agent: Explore Options | Simon           |
+-------------+--------------------------------+-----------------+
| 11          | Article Agent: Implement basic | Simon           |
|             | Solution                       |                 |
+-------------+--------------------------------+-----------------+
| 12          | Article Agent: Implement tool  | Simon           |
|             | calling, refactor Article Agent|                 |
+-------------+--------------------------------+-----------------+
| 13          | Captum: Create Captum plots    | Simon           |
|             | for DS1                        |                 |
+-------------+--------------------------------+-----------------+
| 14          | Captum: Create Captum plots    | Simon           |
|             | for DS2                        |                 |
+-------------+--------------------------------+-----------------+



: Work packages. {#tbl-wps}

## Timeline 

[Describe who worked on which work package and when]

+-------------+--------------------------------+
| KW          | Package No.                    |
+=============+================================+
| 40          | 1                              |
+-------------+--------------------------------+
| 41          | 1, 7                           |
+-------------+--------------------------------+
| 42          | 2, 7, 9                        |
+-------------+--------------------------------+
| 43          | 5, 6, 10                       |
+-------------+--------------------------------+
| 44          | 3, 6, 10, 11                   |
+-------------+--------------------------------+
| 45          | 3, 6, 11                       |
+-------------+--------------------------------+
| 46          | 3, 6, 11                       |
+-------------+--------------------------------+
| 47          | 6, 11                          |
+-------------+--------------------------------+
| 48          | 6, 8, 13                       |
+-------------+--------------------------------+
| 49          | 4, 6                           |
+-------------+--------------------------------+
| 50          | 4, 6, 12                       |
+-------------+--------------------------------+
| 51          | 4, 6, 12, 14                   |
+-------------+--------------------------------+
| 52          | 6, 12                          |
+-------------+--------------------------------+
| 1           |                                |
+-------------+--------------------------------+
| 2           |                                |
+-------------+--------------------------------+


